# Generated by Django 2.2.2 on 2019-08-05 07:55

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=15, unique=True)),
                ('img', models.ImageField(default='imgs/default_food.png', upload_to=food.models.imgUpload)),
                ('price', models.IntegerField(default=1)),
                ('desc', models.TextField(default='', max_length=300)),
                ('oneline_desc', models.CharField(default='맛있는 음식', max_length=30)),
                ('creator', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FoodBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_book_name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(default='imgs/food_book_default.jpg', max_length=40, upload_to=food.models.imgUpload)),
                ('star', models.IntegerField(default=0)),
                ('food', models.ManyToManyField(to='food.Food')),
            ],
        ),
    ]
