# Generated by Django 2.2.2 on 2019-08-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='creator',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='desc',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
