# Generated by Django 2.2.2 on 2019-08-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190825_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
