# Generated by Django 2.2.2 on 2019-08-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_foodsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(default=1, to='food.FoodSubCategory'),
        ),
    ]
