# Generated by Django 2.2.3 on 2019-09-09 11:11

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_foodbook_playcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='sub_img',
            field=models.ImageField(blank=True, upload_to=food.models.imgUpload),
        ),
    ]
