# Generated by Django 2.2.3 on 2019-09-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_food_sub_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='sub_creator',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
