# Generated by Django 2.2.2 on 2019-09-12 02:50

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_food_sub_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.AddField(
            model_name='food',
            name='order',
            field=models.IntegerField(default=food.models.getLastOrderForGoal),
        ),
    ]
