# Generated by Django 2.2.2 on 2019-09-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20190912_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
