# Generated by Django 2.2.2 on 2019-09-12 02:53

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_remove_food_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='order',
            field=models.IntegerField(default=food.models.getLastOrderForGoal),
        ),
    ]
