# Generated by Django 2.2.2 on 2019-09-12 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20190912_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='order',
            new_name='priority',
        ),
    ]
