# Generated by Django 2.2.2 on 2019-09-12 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20190912_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='priority',
            new_name='order',
        ),
    ]
