# Generated by Django 2.2.2 on 2019-09-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_remove_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
