# Generated by Django 2.2.2 on 2019-09-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_remove_food_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
