# Generated by Django 2.2.2 on 2019-08-31 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0004_food_category'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('hashId', models.CharField(max_length=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='TestRowOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left', to='food.Food')),
                ('right_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right', to='food.Food')),
            ],
        ),
        migrations.CreateModel(
            name='TestRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_test.TestRowOne')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_test.FoodTest')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_test.TestRows')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_test.FoodTest')),
            ],
        ),
    ]
