# Generated by Django 2.2.2 on 2019-09-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtest',
            name='hashId',
        ),
    ]
