# Generated by Django 2.2.2 on 2019-08-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('food_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_test.TestRowOne')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_test.FoodTest')),
            ],
        ),
    ]
