# Generated by Django 2.2.2 on 2019-08-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('food_test', '0002_testrows'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrows',
            name='member',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
            preserve_default=False,
        ),
    ]
