# Generated by Django 2.2.2 on 2019-09-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_test', '0002_remove_foodtest_hashid'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtest',
            name='hashId',
            field=models.CharField(default='abcde', max_length=5),
            preserve_default=False,
        ),
    ]
