# Generated by Django 2.2.2 on 2019-09-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_test', '0003_foodtest_hashid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantanswer',
            name='test',
        ),
    ]
