# Generated by Django 2.2.2 on 2019-08-07 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('food', '0001_initial'),
        ('food_test', '0003_testrows_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_test.TestRows')),
            ],
        ),
    ]
