# Generated by Django 2.2.2 on 2019-08-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_test', '0005_foodtest_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtest',
            old_name='participants',
            new_name='participant',
        ),
    ]
