# Generated by Django 2.2.2 on 2019-08-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_test', '0006_auto_20190809_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtest',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='part', to='member.Member'),
        ),
    ]
