# Generated by Django 2.2.2 on 2019-08-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_test', '0007_auto_20190809_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrows',
            name='answer',
        ),
    ]
