# Generated by Django 2.2.2 on 2019-08-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('food_test', '0008_remove_testrows_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrows',
            name='answer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='food.Food'),
            preserve_default=False,
        ),
    ]
