# Generated by Django 2.2.2 on 2019-08-24 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_test', '0010_foodtest_hashid'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantanswer',
            name='test',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='food_test.FoodTest'),
            preserve_default=False,
        ),
    ]
