# Generated by Django 2.2.2 on 2019-08-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_test', '0011_participantanswer_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtest',
            name='participant',
        ),
    ]
