# Generated by Django 2.2.2 on 2019-08-06 14:57

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=20)),
                ('session_key', models.CharField(default='', max_length=50)),
                ('birth_year', models.IntegerField()),
                ('birth_month', models.IntegerField(default=1)),
                ('birth_day', models.IntegerField(default=1)),
                ('imgs', models.ImageField(default='imgs/default_profile.png', upload_to=member.models.imgUpload)),
                ('favorite_book', models.ManyToManyField(blank=True, to='food.FoodBook')),
            ],
        ),
    ]
