# Generated by Django 2.2.3 on 2019-09-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_year',
            field=models.IntegerField(default=1997),
        ),
    ]
